version: 2.1

executors: 
  hugo-executor:
    docker:
      - image: lnhcode/hugo:latest
    working_directory: ~/greenelephant.io/
  aws-cli-executor:
    docker:
      - image: infrastructureascode/aws-cli:1.16.229
    working_directory: ~/greenelephant.io/

jobs:
  build:
    executor: hugo-executor
    steps:
      - checkout
      - run: hugo
      - persist_to_workspace:
          root: ~/greenelephant.io/
          paths:
            - public
  deploy:
    executor: aws-cli-executor
    steps:
      - attach_workspace:
          at: ~/greenelephant.io/
      - run: aws s3 delete <params>
      - run: aws s3 sync <param>

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
